<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\T3Interpreter\T3Interpreter.csproj" />
    <ProjectReference Include="..\T3Compiler\T3Compiler.csproj" />
  </ItemGroup>
</Project>